version: '3.3'

services:
  tfserving_adder:
    container_name: tfserving_adder
    image: 'tensorflow/serving:latest'
    ports:
      - '8501:8501'
    volumes:
      - type: bind
        source: ./tmp/adder
        target: /models/adder
    environment:
      MODEL_NAME: adder
